version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myrealtrip-renewal:latest
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./certs:/etc/letsencrypt
      - ./public:/usr/share/nginx/html
    logging:
      driver: awslogs
      options:
        awslogs-group: myrealtrip-renewal
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: nginx
    # volumes:
    #   - ./logs:/var/log/nginx

 