name: Production Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Test
        run: |
          npm ci
          npm run build
          npm test
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myrealtrip-renewal:latest

  deploy:
    needs: build-test-scan
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Get secrets from SSM
        run: |
          aws ssm get-parameters-by-path --path /prod/myrealtrip/ --with-decryption --region ap-northeast-2 > secrets.json
          export $(cat secrets.json | jq -r '.Parameters[] | "\(.Name | split("/") | .[-1])=\(.Value)"')
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to ECR
        run: |
          docker build -t ${{ secrets.ECR_REPO }}:${{ github.sha }} .
          docker push ${{ secrets.ECR_REPO }}:${{ github.sha }}
      - name: Update ECS service
        uses: aws-actions/amazon-ecs-update-task-definition@v1
        with:
          task-definition: ${{ secrets.ECS_TASK_DEF }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Vercel/Netlify/Amplify 등 PR Preview 연동 스텝 추가 